//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=FreshMart;Integrated Security=True")]
        public string FreshMartConnectionString {
            get {
                return ((string)(this["FreshMartConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.174,1433;Initial Catalog=sun89911_dropup;Persist Security In" +
            "fo=True;User ID=sun89911_haiit")]
        public string sun89911_dropupConnectionString1 {
            get {
                return ((string)(this["sun89911_dropupConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.174,1433;Initial Catalog=sun89911_drop_up;User ID=sun89911_h" +
            "aiit;Password=Ngochaiit257!")]
        public string sun89911_drop_upConnectionString {
            get {
                return ((string)(this["sun89911_drop_upConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.174,1433;Initial Catalog=sun89911_dropup;User ID=sun89911_ha" +
            "idn;Password=Ngochaiit257!")]
        public string sun89911_dropupConnectionString {
            get {
                return ((string)(this["sun89911_dropupConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.174,1433;Initial Catalog=sun89911_dropup;Persist Security In" +
            "fo=True;User ID=sun89911_haidn;Password=Ngochaiit257!")]
        public string sun89911_dropupConnectionString2 {
            get {
                return ((string)(this["sun89911_dropupConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Yuncosplayvn;Integrated Security=True" +
            "")]
        public string YuncosplayvnConnectionString {
            get {
                return ((string)(this["YuncosplayvnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_yuncosplayvn;Persist Secur" +
            "ity Info=True;User ID=yun44832_haiit;Password=Ngochaiit257!")]
        public string yun44832_yuncosplayvnConnectionString {
            get {
                return ((string)(this["yun44832_yuncosplayvnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_yuncosplayvn;Persist Secur" +
            "ity Info=True;User ID=yun44832_haiit")]
        public string yun44832_yuncosplayvnConnectionString1 {
            get {
                return ((string)(this["yun44832_yuncosplayvnConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_db_yuncosplay;Persist Secu" +
            "rity Info=True;User ID=yun44832_db_haiit;Password=Ngochaiit257!")]
        public string yun44832_db_yuncosplayConnectionString {
            get {
                return ((string)(this["yun44832_db_yuncosplayConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_yuncosplaydb;Persist Secur" +
            "ity Info=True;User ID=yun44832_db_haiit;Password=Ngochaiit257!")]
        public string yun44832_yuncosplaydbConnectionString {
            get {
                return ((string)(this["yun44832_yuncosplaydbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Genez;Integrated Security=True")]
        public string GenezConnectionString {
            get {
                return ((string)(this["GenezConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Morcar;Integrated Security=True")]
        public string MorcarConnectionString {
            get {
                return ((string)(this["MorcarConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_morcar.vn;Persist Security " +
            "Info=True;User ID=mor97544_haiit;Password=Ngochaiit257!")]
        public string mor97544_morcar_vnConnectionString {
            get {
                return ((string)(this["mor97544_morcar_vnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_morcarvn;Persist Security I" +
            "nfo=True;User ID=mor97544_haiit;Password=Ngochaiit257!")]
        public string mor97544_morcarvnConnectionString {
            get {
                return ((string)(this["mor97544_morcarvnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_morcarvn;Persist Security I" +
            "nfo=True;User ID=mor97544_haidn")]
        public string mor97544_morcarvnConnectionString1 {
            get {
                return ((string)(this["mor97544_morcarvnConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_dbtest;Persist Security In" +
            "fo=True;User ID=yun44832_dbtest;Password=Ngochaiit257!")]
        public string yun44832_dbtestConnectionString {
            get {
                return ((string)(this["yun44832_dbtestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_dbtest;Persist Security In" +
            "fo=True;User ID=yun44832_dbtest")]
        public string yun44832_dbtestConnectionString1 {
            get {
                return ((string)(this["yun44832_dbtestConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_dbtest;Persist Security In" +
            "fo=True;User ID=yun44832_db_haiit")]
        public string yun44832_dbtestConnectionString2 {
            get {
                return ((string)(this["yun44832_dbtestConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.210,1433;Initial Catalog=yun44832_dbtest;Persist Security In" +
            "fo=True;User ID=yun44832_db_haiit;Password=Ngochaiit257!")]
        public string yun44832_dbtestConnectionString3 {
            get {
                return ((string)(this["yun44832_dbtestConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=TriMunBaLao;Integrated Security=True")]
        public string TriMunBaLaoConnectionString {
            get {
                return ((string)(this["TriMunBaLaoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=SerumBaLao;Integrated Security=True")]
        public string SerumBaLaoConnectionString {
            get {
                return ((string)(this["SerumBaLaoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_morcardb;Persist Security I" +
            "nfo=True;User ID=mor97544_haidn;Password=Ngochaiit257!")]
        public string mor97544_morcardbConnectionString {
            get {
                return ((string)(this["mor97544_morcardbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_dbtest;Persist Security Inf" +
            "o=True;User ID=mor97544_haidn;Password=Ngochaiit257!")]
        public string mor97544_dbtestConnectionString {
            get {
                return ((string)(this["mor97544_dbtestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_test2;Persist Security Info" +
            "=True;User ID=mor97544_test2;Password=3z65V~um")]
        public string mor97544_test2ConnectionString {
            get {
                return ((string)(this["mor97544_test2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.74,1433;Initial Catalog=mor97544_test2;Persist Security Info" +
            "=True;User ID=mor97544_haidn;Password=Ngochaiit257!")]
        public string mor97544_test2ConnectionString1 {
            get {
                return ((string)(this["mor97544_test2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.42,1433;Initial Catalog=bal77102_serumbalaodb;Persist Securi" +
            "ty Info=True;User ID=bal77102_haiit;Password=Ngochaiit257!")]
        public string bal77102_serumbalaodbConnectionString {
            get {
                return ((string)(this["bal77102_serumbalaodbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=DropupDB;Integrated Security=True")]
        public string DropupDBConnectionString {
            get {
                return ((string)(this["DropupDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=BIHA-Group;Integrated Security=True")]
        public string BIHA_GroupConnectionString {
            get {
                return ((string)(this["BIHA_GroupConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Vosella;Integrated Security=True")]
        public string VosellaConnectionString {
            get {
                return ((string)(this["VosellaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.36,1433;Initial Catalog=vos45758_db;Persist Security Info=Tr" +
            "ue;User ID=vos45758_haiit;Password=Ngochaiit257!")]
        public string vos45758_dbConnectionString {
            get {
                return ((string)(this["vos45758_dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=DLD-Group;Integrated Security=True")]
        public string DLD_GroupConnectionString {
            get {
                return ((string)(this["DLD_GroupConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.36,1433;Initial Catalog=mul96217_multiagrodb;Persist Securit" +
            "y Info=True;User ID=mul96217_haiit;Password=Ngochaiit257!")]
        public string mul96217_multiagrodbConnectionString {
            get {
                return ((string)(this["mul96217_multiagrodbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Dino;Integrated Security=True")]
        public string DinoConnectionString {
            get {
                return ((string)(this["DinoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.28,1433;Initial Catalog=sto59554_dinodb;Persist Security Inf" +
            "o=True;User ID=sto59554_haiit;Password=Ngochaiit257!")]
        public string sto59554_dinodbConnectionString {
            get {
                return ((string)(this["sto59554_dinodbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.28,1433;Initial Catalog=sto59554_dinodatabase;Persist Securi" +
            "ty Info=True;User ID=sto59554_haiit;Password=Ngochaiit257!")]
        public string sto59554_dinodatabaseConnectionString {
            get {
                return ((string)(this["sto59554_dinodatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Elysien;Integrated Security=True")]
        public string ElysienConnectionString {
            get {
                return ((string)(this["ElysienConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73;Initial Catalog=ely20147_elysiendb;Persist Security Info=" +
            "True;User ID=ely20147_haiit;Password=Ngochaiit257!")]
        public string ely20147_elysiendbConnectionString {
            get {
                return ((string)(this["ely20147_elysiendbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.42,1433;Initial Catalog=ely60663_elysiendb;Persist Security " +
            "Info=True;User ID=ely60663_haiit;Password=Ngochaiit257!")]
        public string ely60663_elysiendbConnectionString {
            get {
                return ((string)(this["ely60663_elysiendbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.152.165.150\\MSSQLSERVER2019;Initial Catalog=elysiendb;Persist Sec" +
            "urity Info=True;User ID=elysienv;Password=Ngochaiit257!")]
        public string elysiendbConnectionString {
            get {
                return ((string)(this["elysiendbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Tokaido;Integrated Security=True")]
        public string TokaidoConnectionString {
            get {
                return ((string)(this["TokaidoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.28;Initial Catalog=sto59554_dinodb;Persist Security Info=Tru" +
            "e;User ID=sto59554_haiit;Password=Ngochaiit257!")]
        public string sto59554_dinodbConnectionString1 {
            get {
                return ((string)(this["sto59554_dinodbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.28;Initial Catalog=sto59554_dinodatabase;Persist Security In" +
            "fo=True;User ID=sto59554_haiit2;Password=Ngochaiit257!")]
        public string sto59554_dinodatabaseConnectionString1 {
            get {
                return ((string)(this["sto59554_dinodatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.152.165.150\\MSSQLSERVER2019;Initial Catalog=elysienv_tokaidodb;Pe" +
            "rsist Security Info=True;User ID=elysienv;Password=Ngochaiit257!")]
        public string elysienv_tokaidodbConnectionString {
            get {
                return ((string)(this["elysienv_tokaidodbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.36,1433\\MSSQLSERVER2019;Initial Catalog=mul96217_multiagrodb" +
            ";Persist Security Info=True;User ID=mul96217_haiit;Password=Ngochaiit257!")]
        public string mul96217_multiagrodbConnectionString1 {
            get {
                return ((string)(this["mul96217_multiagrodbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=NhomDucMinhThinh;Integrated Security=" +
            "True")]
        public string NhomDucMinhThinhConnectionString {
            get {
                return ((string)(this["NhomDucMinhThinhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=Bunny;Integrated Security=True")]
        public string BunnyConnectionString {
            get {
                return ((string)(this["BunnyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73;Initial Catalog=bun53642_bunnydb;Persist Security Info=Tr" +
            "ue;User ID=bun53642_haiit;Password=Ngochaiit257!")]
        public string bun53642_bunnydbConnectionString {
            get {
                return ((string)(this["bun53642_bunnydbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73;Initial Catalog=bun53642_bunny;Persist Security Info=True" +
            ";User ID=bun53642_haiit;Password=Ngochaiit257!")]
        public string bun53642_bunnyConnectionString {
            get {
                return ((string)(this["bun53642_bunnyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73;Initial Catalog=bun53642_db;Persist Security Info=True;Us" +
            "er ID=bun53642_haiit;Password=Ngochaiit257!")]
        public string bun53642_dbConnectionString {
            get {
                return ((string)(this["bun53642_dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=HMmedia;Integrated Security=True")]
        public string HMmediaConnectionString {
            get {
                return ((string)(this["HMmediaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73,1433;Initial Catalog=hmm85459_hmmediadb;Persist Security " +
            "Info=True;User ID=hmm85459_haiit;Password=Ngochaiit257!")]
        public string hmm85459_hmmediadbConnectionString {
            get {
                return ((string)(this["hmm85459_hmmediadbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73,1433;Initial Catalog=bun53642_bunnydb;Persist Security In" +
            "fo=True;User ID=bun53642_haiit;Password=Ngochaiit257!")]
        public string bun53642_bunnydbConnectionString1 {
            get {
                return ((string)(this["bun53642_bunnydbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=BachGiaiClinic;Integrated Security=Tr" +
            "ue")]
        public string BachGiaiClinicConnectionString {
            get {
                return ((string)(this["BachGiaiClinicConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73,1433;Initial Catalog=dak00318_dakhoabachgiaidb;Persist Se" +
            "curity Info=True;User ID=dak00318_haiit;Password=Ngochaiit257!")]
        public string dak00318_dakhoabachgiaidbConnectionString {
            get {
                return ((string)(this["dak00318_dakhoabachgiaidbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=BioViet;Integrated Security=True")]
        public string BioVietConnectionString {
            get {
                return ((string)(this["BioVietConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.112,1433;Initial Catalog=bio03550_biovietdb;Persist Security" +
            " Info=True;User ID=bio03550_haiit;Password=Ngochaiit257!")]
        public string bio03550_biovietdbConnectionString {
            get {
                return ((string)(this["bio03550_biovietdbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=TPAlock;Integrated Security=True")]
        public string TPAlockConnectionString {
            get {
                return ((string)(this["TPAlockConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.112,1433;Initial Catalog=tpa19428_tpalockdb;Persist Security" +
            " Info=True;User ID=tpa19428_haiit;Password=Ngochaiit257!")]
        public string tpa19428_tpalockdbConnectionString {
            get {
                return ((string)(this["tpa19428_tpalockdbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=VinaFocus;Integrated Security=True")]
        public string VinaFocusConnectionString {
            get {
                return ((string)(this["VinaFocusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.78.2.73,1433;Initial Catalog=vin10795_vinafocusdb;Persist Securit" +
            "y Info=True;User ID=vin10795_haiit;Password=Ngochaiit257!")]
        public string vin10795_vinafocusdbConnectionString {
            get {
                return ((string)(this["vin10795_vinafocusdbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A9CMMFQ;Initial Catalog=LisPharma;Integrated Security=True")]
        public string LisPharmaConnectionString {
            get {
                return ((string)(this["LisPharmaConnectionString"]));
            }
        }
    }
}
