//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshMart_Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_notification
    {
        public long system_notification_id { get; set; }
        public string system_notification_title { get; set; }
        public Nullable<System.DateTime> system_notification_create_datetime { get; set; }
    }
}
